version: '3'
services:
  eureka:
    build: eureka/
    ports: 
      - 8761:8761
    networks:
      services-network-01:
        aliases:
          - eureka
    
  product-core:
    build: productcore/
    ports: 
      - 8012:8012 
    depends_on:
      - eureka
      - turbine
    links:
      - eureka
    restart: always
    networks:
      services-network-01:
        aliases:
          - product-core

  user-core:
    build: usercore/
    ports: 
      - 8001:8001 
    depends_on:
      - eureka
      - turbine
    links:
      - eureka
    restart: always
    networks:
      services-network-01:
        aliases:
          - user-core

  category-core:
    build: categorycore/
    ports: 
      - 8003:8003 
    depends_on:
      - eureka
      - turbine
    links:
      - eureka
    restart: always
    networks:
      services-network-01:
        aliases:
          - category-core

  product-composite:
    build: productcomposite/
    ports: 
      - 8004:8004
    depends_on:
      - eureka
      - category-core
      - product-core
    links:
      - eureka
    networks:
      services-network-01:
        aliases:
          - product-composite

  turbine:
    build: turbine/
    ports: 
      - 8082:8082
    depends_on:
      - eureka
    links:
      - eureka
    restart: always
    networks:
      services-network-01:
        aliases:
          - turbine
  zuul:
    build: zuul/
    ports: 
      - 8081:8081
    depends_on:
      - eureka
      - product-composite
    links:
      - eureka
    networks:
      services-network-01:
        aliases:
          - zuul
  client:
    build:
      context: client/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      services-network-01:
        aliases:
          - zuul

networks:
  services-network-01:
    name: services-network-01
    driver: bridge