version: '3'
services:
  eureka:
    build: eureka/
    ports: 
      - 8761:8761
    
  products-core:
    build: productcore/
    ports: 
      - 8002:8002 
    depends_on:
      - eureka
    links:
      - eureka
    restart: always

  turbine:
    build: turbine/
    ports: 
      - 8082:8082
    depends_on:
      - eureka
    links:
      - eureka
    restart: on-failure