version: '3'
services:
  eureka:
    build: eureka/
    ports: 
      - 8761:8761
    
  product-core:
    build: productcore/
    ports: 
      - 8012:8012 
    depends_on:
      - eureka
      - turbine
    links:
      - eureka
    restart: always

  user-core:
    build: usercore/
    ports: 
      - 8001:8001 
    depends_on:
      - eureka
      - turbine
    links:
      - eureka
    restart: always

  category-core:
    build: categorycore/
    ports: 
      - 8003:8003 
    depends_on:
      - eureka
      - turbine
    links:
      - eureka
    restart: always

  product-composite:
    build: productcomposite/
    ports: 
      - 8004:8004
    depends_on:
      - eureka
      - category-core
      - product-core
    links:
      - eureka

  turbine:
    build: turbine/
    ports: 
      - 8082:8082
    depends_on:
      - eureka
    links:
      - eureka
    restart: always
  zuul:
    build: zuul/
    ports: 
      - 8081:8081
    depends_on:
      - eureka
      - product-composite
    links:
      - eureka