version: '3'
services:
  eureka:
    build: eureka/
    ports: 
      - 8761:8761

  turbine:
    build: turbine/
    ports: 
      - 8082:8082
    depends_on:
      - eureka
    links:
      - eureka
    restart: on-failure