# curl webshop:secret@localhost:8001/oauth/token -d grant_type=password -d username=pape123 -d password=pape123 -d scope=write
### Create user
POST   http://localhost:8001/users/
content-type: application/json

{
   "username": "beju",
  "firstname": "be",
   "lastname": "ju",
  "password": "beju",
  "roletype": "admin",
  "rolelevel": 0
}
### Log User in
POST http://webshop:secret@localhost:8001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=beju&password=beju&scope=write

### wir gehen über zuul.
GET http://localhost:8081/productscomposite-service/products/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ii9KVFllcmx4dWpYOVRjMEdIUTlQbG1OVnJ0ajAwNCtuUnJER0g3cldFOEE9In0.eyJleHAiOjE2MTAyNTIzNTMsInVzZXJfbmFtZSI6ImJlanUiLCJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJqdGkiOiIyNzgzYWNjYS0yYWRhLTQ2M2ItOTg0Ny05ZGRhYTY0ZDY5M2EiLCJjbGllbnRfaWQiOiJ3ZWJzaG9wIiwic2NvcGUiOlsid3JpdGUiXX0.ik25-kZE0EAliPi8iAHMb_0Lb8XDyeK2GfWpP6GTo4hX-ARM6E38GJBcbrfGv_A6VY3VZgK_FCRyG40Ru1I8G0tknH4zM38KXvDjm7XKYNjEIvW0xcDgJ5kziXNue2N259xiStDDZGLyC6UlOwPGtwAXxDh1Yx6veGifwGaACkhd9uhYk4rhvJbwG5LIP8VMo3kbcHsAMlLaMRMzCYXv9gq-UyUxel8mJmaSUEqfMRvXRu4jdcRhaKwloveI3_D5nrDonYomtyt2rpDDQjkl0ISQWDNvrxGmTielr-YDhzZ4thDZPQr_dpT9Hp-Dhr9A3lwjSx9zxnThVGESiGQOoA
Cache-Control: no-cache
###
GET http://localhost:8081/productscomposite-service/products/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImwvdkFUNW94VTBuWTdsNVYzMjMxTmVPeXV4WEVRMmJxTnNIRXV3RUN4Sjg9In0.eyJleHAiOjE2MTAyNDQyODMsInVzZXJfbmFtZSI6ImJlanUiLCJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJqdGkiOiJkNDU2YzU2Yi0wMTE3LTQ4MjgtOGVlMi1jYTA2N2Q1YjViNDgiLCJjbGllbnRfaWQiOiJ3ZWJzaG9wIiwic2NvcGUiOlsid3JpdGUiXX0.FhDtkVh5f5QCmnKzgO3DkaY946OHTFuBBryDUEk86weHxAsG1UByGlQFFv9n9bUWWQurCf5h6PT4ZSOPCxebrP_aKPpmV-60u7OnuztRjxpfUgcjyWySJjTZUL-P3mwf6L9Pa4-It_4lrTsb9mSoFUOY0D4vU5Qmus6T0vPGoDtNMmyRKYkvrAgYald839_TtNj7tpVATYADp2aLwVtu_xRQRclcT8F3RGDLLzEYdZN7O6IYzz05m6lw2HweHpusp84rvcAD56XZIvORvcMV8QF4nCkJxDqmrhUXZjPZtJj1ARpSqXXVSXcaWAwJkEBennE-DpxNvnAoRh8v6_vwWg
Cache-Control: no-cache

### Direkt
GET http://localhost:8004/products/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijk3VDlhV3d3Nk5zNktUREcrbmFnREdKY1ZGRlhjdFJDN2FjeE8wWDVlaXM9In0.eyJleHAiOjE2MTAyNDMyMDYsInVzZXJfbmFtZSI6ImJlanUiLCJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJqdGkiOiIzOTA1ZGUwZC1iYTI4LTRiMmEtOTM0NC04ZDFhNDVmYTRlOTciLCJjbGllbnRfaWQiOiJ3ZWJzaG9wIiwic2NvcGUiOlsid3JpdGUiXX0.hbku3hbFoClmlW9zN7NC4Ke8b4WiNsXC80cGZ3h3e6qC2cOFtwLBM_oSfR6LlBHHZvaZ7vPgyRybxXh3k3cfHS4FV4aY23spHFVOWaSeJWJfR8DGtYPGZkuP_FQqjdJL82jAYRvFBKzm2LHI2_aUArgbWWZnnDWlhaM0d289XChXBdBYucJ0viibzshpfIG9mUvAsJRF9-buNBOfhjTg4HciNMo2Yr23avVC9qGBCapjqvibvPpK6sliiwFo62nOuzI7_TiaCcS7PnS9MAaAiIS0VwEQKxZZxuvRQcpvso-WjQYOnw7MZLCckWAlVOhu0w0zuAL9bCE1PrwIvLlt6g
####

POST http://webshop:secret@localhost:8001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=pape123&password=pape123&scope=write

###


GET http://localhost:8001/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IngrY2h1NDBnMEFLTjcxMTVvbDlJMllhWW5EVXNwRG5qdXhKeTN1RXoxV3M9In0.eyJleHAiOjE2MDk2MzI2MzMsInVzZXJfbmFtZSI6InBhcGUxMjMiLCJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJqdGkiOiJjZTZhZGM4ZS05NzA2LTRmOTYtYTBkZi0xM2U0ZDE4MjI4NmIiLCJjbGllbnRfaWQiOiJ3ZWJzaG9wIiwic2NvcGUiOlsicmVhZCJdfQ.Wyfpe-GdsQnaAtghBbBkm8uPIqYnOR3oD8AZBPPIYW2phQOhGOnp1NVQObSXXapmOtt802TDtzE74NtNSi8dB50OtJk2JMF6G5vrEUEjoJ7lmnomk17DanDO56TVGkw4Eq9uTkC6zg0DXk65aFyigUSGiqp2N4rGfXhlsfclQzI1oWxbq8JJOFiIGTQK8pQ6Pi3L0NYPxSQwdD2ppdIcDKucoNIHmiRhYtFScRnmVvb5zaGaIvKDczpvnrO1_pY-FCOzLkQ2o4JUCKGBD9KTv8_z9nPCupBh4SOHkM2cH6j6fTn4G6lfocHwn_x9kvhQlFmBc5B6qNtIPqpwtZL70w

###
POST   http://localhost:8001/users/
content-type: application/json

{
   "username": "beju",
  "firstname": "be",
   "lastname": "ju",
  "password": "beju",
  "roletype": "admin",
  "rolelevel": 0
}