# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


################################################

#Category core

################################################
GET http://localhost:8003/categories/1
Cache-Control: no-cache
###

GET http://localhost:8003/categories
Cache-Control: no-cache
###

POST http://localhost:8003/categories 
content-type: application/json

{
    "name": "Kaffee",
    "productIds": ""
}

###
PUT  http://localhost:8003/categories/1
content-type: application/json

{
  "id": 1,
 "name": "name",
  "productIds": "1"
}


###

DELETE http://localhost:8003/categories/1
Cache-Control: no-cache
###

################################################

#Product core

################################################

GET http://localhost:8012/products/
Cache-Control: no-cache
####

GET http://localhost:8012/products/1
Cache-Control: no-cache
####

POST http://localhost:8012/products 
content-type: application/json

{
  "name": "test",
  "price": 100.0,
  "categoryId": 1,
  "details": "this detail"
}
###

PUT  http://localhost:8012/products/1
content-type: application/json

{
   "id": 1,
  "name": "update",
  "price": 100.0,
  "categoryId": 1,
  "details": "this detail"
}

###
DELETE http://localhost:8012/products/1
Cache-Control: no-cache
###


################################################

#user core

################################################
GET http://localhost:8001/users/name/beju
Cache-Control: no-cache
####

GET http://localhost:8001/users/1
Cache-Control: no-cache
####
POST   http://localhost:8001/users/
content-type: application/json

{
   "username": "pape123",
  "firstname": "be",
   "lastname": "ju",
  "password": "pape123",
  "roletype": "admin",
  "rolelevel": 1
}
####
PUT   http://localhost:8001/users/1
content-type: application/json

{
    "id": 1,
   "username": "neju",
  "firstname": "be",
   "lastname": "ju",
  "password": "kickerking",
  "roletype": "admin",
  "rolelevel": 1
}
####
DELETE  http://localhost:8001/users/1
Cache-Control: no-cache


################################################

#Zuuuul

################################################

#### Zuuuul Composite

POST  http://localhost:8081/products-core-service/products/
content-type: application/json

{
  "name": "update1",
  "price": 100.0,
  "categoryId": 1,
  "details": "this detail"
}

###
GET http://localhost:8081/products-core-service/products/
Cache-Control: no-cache
####

GET http://localhost:8081/productscomposite-service/products/
Cache-Control: no-cache
####

DELETE http://localhost:8081/productscomposite-service/categories/1
Cache-Control: no-cache

####
POST  http://localhost:8081/productscomposite-service/products/
content-type: application/json

{
  "name": "Koffee",
  "price": 100.0,
  "categoryId": 2,
  "details": "Really expensive Coffee"
}
####
POST  http://localhost:8081/productscomposite-service/products/
content-type: application/json

{
  "name": "Cheaper Coffee",
  "price": 10.0,
  "categoryId": 1,
  "details": "Really cheap Coffee"
}

####
GET http://localhost:8081/productscomposite-service/products/
Cache-Control: no-cache

### maxPrice minPrice searchDescription
##test maxprice
GET http://localhost:8081/productscomposite-service/products?maxPrice=50
Cache-Control: no-cache

###
##test minprice
GET http://localhost:8081/productscomposite-service/products?minPrice=50
Cache-Control: no-cache

###
##search Description
GET http://localhost:8081/productscomposite-service/products?searchDescription=expensive
Cache-Control: no-cache

GET https://example.com/comments?page=2&pageSize=10

###
POST http://localhost:8081/category-core-service/categories 
content-type: application/json

{
    "name": "Kaffee",
    "productIds": ""
}

###
PUT http://localhost:8081/category-core-service/categories/2
content-type: application/json

{
    "id": 2,
    "name": "Tee",
    "productIds": ""
}

###
GET  http://localhost:8081/category-core-service/categories 
content-type: application/json

###

###
GET http://localhost:8081/products-core-service/products/
Cache-Control: no-cache
####


#####################################

##### Test User Via ZUUL

###################################
GET http://localhost:8081/user-core-service/users/name/beju
Cache-Control: no-cache
####

GET http://localhost:8081/user-core-service/users/1
Cache-Control: no-cache
####
POST   http://localhost:8081/user-core-service/users/
content-type: application/json

{
   "username": "beju",
  "firstname": "be",
   "lastname": "ju",
  "password": "kickerking",
  "roletype": "admin",
  "rolelevel": 1
}