server:
  port: 8001
spring:
  application:
    name: user-core-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://localhost:8001/auth/oauth2/keys