management.endpoints.web.exposure.include: hystrix.stream
server:
  port: 8004
spring:
  application:
    name: productscomposite-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"